### ISSUE TITLE
Why using player:UniqueID() instead of SteamID ?

### ISSUE THREAD

**Issue by SeahDokki** [TeamUlysses/utime#12]
Why using player:UniqueID() instead of SteamID ?
How can I get an offline player totaltime when I don't know his uid ?

**Comment by Nayruden** [comment]
This isn't the best place for general questions, but this is an easy one. UniqueID was historically the recommended way of identifying players in GMod. It's now deprecated in the standard swing of GMod API, but we have no immediate plans on changing this.
